version: '3.8'

services:
  app:
    build: .
    container_name: weather_app
    ports:
      - "5000:80"
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=sqlite:///weather.db
      - OPENWEATHERMAP_API_KEY=your_api_key_here
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: weather_db
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  tests:
    build: .
    container_name: weather_tests
    command: python -m unittest discover -s tests
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:///weather.db
      - OPENWEATHERMAP_API_KEY=your_api_key_here
    volumes:
      - .:/app
    depends_on:
      - app
